# Generated by Django 2.1.3 on 2018-12-12 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('first_name', models.CharField(db_column='CST_F_NAME', max_length=75, null=True)),
                ('last_name', models.CharField(db_column='CST_L_NAME', max_length=75, null=True)),
                ('title', models.CharField(db_column='CST_TITLE', max_length=75, null=True)),
                ('customer_number', models.IntegerField(db_column='CST_RBANUM', primary_key=True, serialize=False)),
                ('sale_number', models.IntegerField(db_column='CST_SALENUM')),
                ('company_name', models.CharField(db_column='CST_CONAME', max_length=150)),
                ('bidder_number', models.IntegerField(db_column='CST_BIDNUM')),
                ('country', models.CharField(db_column='CST_COUNTRY', max_length=3)),
                ('purchase_threshold', models.DecimalField(db_column='CST_PUR_THRESHOLD', decimal_places=2, max_digits=13, null=True)),
                ('customer_type', models.CharField(db_column='CST_CUSTOMER_TYPE', max_length=3)),
            ],
            options={
                'db_table': 'GA_Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('lot_num', models.IntegerField(null=True)),
                ('lot_model_name', models.CharField(max_length=15, null=True)),
                ('lot_model_desc', models.CharField(max_length=35, null=True)),
                ('lot_inventoryid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_bidder_number', models.IntegerField(db_column='lot_bidnum', null=True)),
                ('lot_equipment_code', models.CharField(db_column='lot_eqgrpcode', max_length=5, null=True)),
                ('lot_equipment_type', models.CharField(db_column='lot_eqtype', max_length=5, null=True)),
                ('lot_equipment_sub_type', models.CharField(db_column='lot_eqsubtype', max_length=5, null=True)),
                ('lot_sold_price', models.DecimalField(db_column='lot_soldprice', decimal_places=2, max_digits=13, null=True)),
                ('lot_shoot_price', models.DecimalField(db_column='lot_shootprice', decimal_places=2, max_digits=13, null=True)),
                ('lot_inyard_date', models.DateField()),
                ('lot_checkout_date', models.DateField()),
                ('lot_photo', models.CharField(db_column='lot_eei_asset_photo_filename', max_length=48, null=True)),
                ('lot_asset_guid', models.UUIDField(editable=False)),
            ],
            options={
                'db_table': 'GA_Lot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_number', models.IntegerField(db_column='SV_SALENUM', primary_key=True, serialize=False)),
                ('sale_office', models.CharField(db_column='SV_OFFICE', max_length=50, null=True)),
                ('sale_date', models.DateField(db_column='SV_SALEDATE')),
                ('sale_days', models.IntegerField(db_column='SV_SALEDAYS')),
                ('sale_address', models.CharField(db_column='SV_ADDR1', max_length=30)),
                ('sale_address_2', models.CharField(db_column='SV_ADDR2', max_length=30)),
                ('sale_city', models.CharField(db_column='SV_CITY', max_length=30)),
                ('sale_province', models.CharField(db_column='SV_PROV', max_length=25)),
                ('sale_country', models.CharField(db_column='SV_COUNTRY', max_length=25)),
            ],
            options={
                'db_table': 'GA_SaleVars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('ask_price', models.IntegerField()),
            ],
        ),
    ]
