# Generated by Django 2.1.3 on 2018-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_contact_note_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
