# Generated by Django 2.1.3 on 2018-12-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181130_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrifterCustomer',
            new_name='Customer',
        ),
    ]
