# Generated by Django 2.1.3 on 2018-12-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='shoot_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=13),
            preserve_default=False,
        ),
    ]
