# Generated by Django 2.1.3 on 2018-12-03 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='api.Customer'),
        ),
    ]
