# Generated by Django 2.1.3 on 2018-12-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_asset_shoot_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='shoot_price',
            field=models.IntegerField(blank=True),
        ),
    ]
