# Generated by Django 2.1.3 on 2018-12-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_status',
            field=models.CharField(default='UNSENT', max_length=100),
        ),
    ]
