# Generated by Django 2.1.3 on 2018-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181204_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friend',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
