# Generated by Django 2.1.3 on 2018-12-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181204_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='customer',
        ),
        migrations.AddField(
            model_name='gift',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='api.Friend'),
            preserve_default=False,
        ),
    ]
