# Generated by Django 2.1.3 on 2018-12-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181205_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftsuggestion',
            name='customer',
        ),
    ]
