# Generated by Django 2.1.3 on 2018-12-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181213_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.Asset'),
        ),
    ]
