# Generated by Django 2.1.3 on 2018-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181213_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageSid', models.CharField(max_length=40)),
                ('AccountSid', models.CharField(max_length=40)),
                ('MessagingServiceSid', models.CharField(max_length=40)),
                ('From', models.CharField(max_length=40)),
                ('To', models.CharField(max_length=40)),
                ('Body', models.CharField(max_length=40)),
            ],
        ),
    ]
