# Generated by Django 2.1.3 on 2018-12-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_giftsuggestion_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_given', models.DateTimeField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='api.Friend')),
            ],
        ),
        migrations.RemoveField(
            model_name='gift',
            name='date_given',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='price',
        ),
        migrations.AddField(
            model_name='giftrecord',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Gift'),
        ),
    ]
