# Generated by Django 2.1.3 on 2018-12-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181205_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gift_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='giftrecord',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_history', to='api.Friend'),
        ),
    ]
