# Generated by Django 2.1.3 on 2018-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181206_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='source',
            field=models.CharField(default='Amazon', max_length=255),
            preserve_default=False,
        ),
    ]
