# Generated by Django 2.1.3 on 2018-12-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181213_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliomessage',
            name='AccountSid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='ApiVersion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='From',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='FromCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='FromCountry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='FromState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='FromZip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='MessageSid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='MessagingServiceSid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='NumMedia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='NumSegments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='SmsMessageSid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='SmsSid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='SmsStatus',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='ToCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='ToCountry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='ToState',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='twiliomessage',
            name='ToZip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
