# Generated by Django 2.1.3 on 2018-12-07 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_gift_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='specialdate',
            name='date_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SpecialDateType'),
        ),
        migrations.AddField(
            model_name='specialdate',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='api.Friend'),
        ),
    ]
