# Generated by Django 2.1.3 on 2018-12-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='fileName',
            new_name='file_name',
        ),
    ]
