# Generated by Django 2.1.3 on 2018-12-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181213_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliomessage',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_messages', to='api.Contact'),
        ),
    ]
