# Generated by Django 2.1.3 on 2018-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_twiliomessage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='on_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
