# Generated by Django 2.1.3 on 2018-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_asset_on_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='thumbnail_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
