# Generated by Django 2.1.3 on 2018-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181218_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='make',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='shoot_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
