# Generated by Django 2.1.3 on 2018-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181220_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
