# Generated by Django 2.1.3 on 2018-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181220_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='catalog_notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='comes_with',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='usage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
