# Generated by Django 2.1.3 on 2018-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181221_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sale_number',
            field=models.IntegerField(blank=True, default=2019116),
            preserve_default=False,
        ),
    ]
