# Generated by Django 2.1.3 on 2018-12-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181230_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='contact',
            new_name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Asset'),
        ),
    ]
