# Generated by Django 2.1.3 on 2018-12-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucketlist',
            new_name='GrifterCustomer',
        ),
    ]
